version: "3.4"

services:
  manager:
    image: emwjacobson/mchoster_manager:latest
    environment:
      STACK_NAME: 'mchoster'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./manager:/manager
    ports:
      - "8000:8000"
    command: gunicorn -b 0.0.0.0:8000 --reload app:app
    deploy:
      placement:
        constraints:
          - "node.role==manager"
      restart_policy:
        window: 120s

  web:
    image: emwjacobson/mchoster_web:latest
    environment:
      - DEBUG=True
      - SERVER_IP=the.servers.ip
      - SECRET_KEY=ChangeThisToALongRandomStringInProduction
      - ALLOWED_HOSTS=*
    ports:
      - 8888:8000
    volumes:
      - static:/app/static
      # - ./web:/app
    depends_on:
      - manager
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  viz:
    image: dockersamples/visualizer
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - "node.role==manager"

volumes:
  static:
    driver: glusterfs
    name: "docker_gfs/static"
