version: "3"

services:
  manager:
    image: emwjacobson/mchoster_manager:latest
    environment:
      STACK_NAME: 'mchoster'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - "node.role==manager"
      restart_policy:
        window: 120s