version: "3"
services:
  db:
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=web
      - MYSQL_USER=web
      - MYSQL_PASSWORD=NotSoSecretPasswd
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db_dev:/var/lib/mysql
  manager:
    build: manager
    image: mchoster_manager:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./manager:/manager
    command: "flask run -h 0.0.0.0 -p 80 --debugger --reload"
    ports:
      - 8080:80
  web:
    build: web
    image: mchoster_web:latest
    environment:
      - SERVER_IP=192.168.1.112
      - MYSQL_DATABASE=web
      - MYSQL_USER=web
      - MYSQL_PASSWORD=NotSoSecretPasswd
      - SECRET_KEY=ChangeThisToALongRandomStringInProduction
      - ALLOWED_HOSTS=192.168.1.112
    depends_on:
      - db
      - manager
    ports:
      - 8888:80
    volumes:
      - ./web:/app
    command: wait-for-it.sh db:3306 -- python3 manage.py runserver --insecure 0:80

volumes:
  db_dev:
