version: "3"
services:
  db:
    build: db
    image: mchoster_db:latest
    environment:
      - MYSQL_DATABASE=web
      - MYSQL_USER=web
      - MYSQL_PASSWORD=NotSoSecretPasswd
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql
  manager:
    build: manager
    image: mchoster_manager:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    build: web
    image: mchoster_web:latest
    depends_on:
      - db
      - manager
    ports:
      - "8080:80"

volumes:
  db:
