version: "3"
services:
  db:
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=web
      - MYSQL_USER=web
      - MYSQL_PASSWORD=ChangeThisPassword
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
  manager:
    build: manager
    image: mchoster_manager:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MAX_SERVERS=10
    restart: unless-stopped
  web:
    build: web
    image: mchoster_web:latest
    environment:
      - SERVER_IP=the.servers.ip
      - MYSQL_DATABASE=web
      - MYSQL_USER=web
      - MYSQL_PASSWORD=ChangeThisPassword
      - SECRET_KEY=ChangeThisToALongRandomStringInProduction
      - ALLOWED_HOSTS=your.website.com
    depends_on:
      - db
      - manager
    volumes:
      - static:/app/static
    restart: unless-stopped
  nginx:
    image: nginx:1.19
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/data/default.conf:/etc/nginx/conf.d/default.conf
      - static:/serve/static
    restart: unless-stopped

volumes:
  db:
  static:
