version: "3.4"

services:
  manager:
    image: emwjacobson/mchoster_manager:latest
    environment:
      STACK_NAME: 'mchoster'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  web:
    image: emwjacobson/mchoster_web:latest
    environment:
      - SERVER_IP=the.servers.ip
      - SECRET_KEY=ChangeThisToALongRandomStringInProduction
      - ALLOWED_HOSTS=your.website.com
    volumes:
      - static:/app/static
    deploy:
      replicas: 2

  nginx:
    image: emwjacobson/mchoster_nginx:latest
    ports:
      - "80:80"
    volumes:
      - static:/serve/static
    deploy:
      replicas: 2

volumes:
  static:
    driver: glusterfs
    name: "docker_gfs/static"
