version: "3"
services:
  db:
    image: "mariadb:10.5"
    environment:
      - MYSQL_DATABASE=web
      - MYSQL_USER=web
      - MYSQL_PASSWORD=NotSoSecretPasswd
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql
  manager:
    build: manager
    image: mchoster_manager:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    build: web
    image: mchoster_web:latest
    depends_on:
      - db
      - manager
    volumes:
      - static:/app/static
  nginx:
    image: nginx:latest
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/data/default.conf:/etc/nginx/conf.d/default.conf
      - static:/serve/static

volumes:
  db:
  static:
